export const WIN_RATE = 'WIN_RATE';
export const FEES = 'FEES';
export const PNL_USD = 'PNL_USD';
export const PNL2_USD = 'PNL2_USD';
export const PNL_AVERAGE_PERCENT = 'PNL_AVERAGE_PERCENT';
export const AMOUNT_OF_SWAPS = 'AMOUNT_OF_SWAPS';
export const AMOUNT_OF_TOKENS = 'AMOUNT_OF_TOKENS';
export const AMOUNT_IN_USD_AVG = 'AMOUNT_IN_USD_AVG';
export const AMOUNT_IN_USD_MEDIAN = 'AMOUNT_IN_USD_MEDIAN';
export const PNL_OF_TOKENS_WITH_AMOUNT_IN_MORE_THAN_AVG =
  'PNL_OF_TOKENS_WITH_AMOUNT_IN_MORE_THAN_AVG';
